config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/UserMissionStatusesTable.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 2017/03/10
 * Time: 17:45
 */

namespace App\Model\Table;

use Cake\ORM\Table;


class UserMissionStatusesTable extends Table {


    public function initialize(array $config)
    {
        // MasterテーブルのidとStatusesテーブルのmission_idは結合の為のキー
        $this->belongsTo('MissionMasters')->setForeignKey('mission_id')->setJoinType('INNER');
        $this->addBehavior('Timestamp');
    }






}

src/Controller/MypagesController.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 2017/03/10
 * Time: 16:12
 * マイページ
 */

namespace App\Controller;

use App\Controller\AppController;
use App\Model\Table\MissionMastersTable;
use App\Model\Table\UserMissionStatusesTable;
use Cake\ORM\TableRegistry;
use Cake\Datasource\ConnectionManager;

class MypagesController extends AppController {
    // 一覧表示
    
    public function index()
    {
        // ログインチェック
        $user_id = $this->Auth->user('id');
        if ($user_id ==null)
        {
            return $this->redirect($this->Auth->redirectUrl('/users/login'));
        }

        // ここから各モデルをロード　(トロフィーを基準にした処理が必要ならここから先のロジックをコピーするか共通化)
        $this->loadModel('Articles');
        $this->loadModel('Scores');
        $this->loadModel('Trophies');
        $this->loadModel('Users');
        $this->loadModel('MissionMasters');
        $this->loadModel('UserMissionStatuses');
        $this->loadModel('UserProfiles');


        // ユーザー名取得
        $users = $this->Users->find('all', array('conditions' => array('Users.id' =>$user_id)));
        $row = $users->first();
        $this->set('users',$row);

        // プロフィール取得
        $profiles = $this->UserProfiles->find('all', array('conditions' => array('UserProfiles.user_id' =>$user_id)));
        $profile = $profiles->first();
        $this->set('profile',$profile);

        // ログインユーザーIDで投稿をソート
        $articles = $this->Articles->find('all', array('conditions'=>array('Articles.user_id' => $user_id,)));
        $this->set(compact('articles'));

        // ログインユーザーIDでイイネされたスコアを集計
        $score_query = $this->Scores->find('all', array('conditions'=>array('Scores.target_user_id' => $user_id)));
        $my_score = $score_query->count();
        $this->set('my_score',$my_score);

        // ログインユーザーIDに対してイイネしたスコアを集計
        $exam_query = $this->Scores->find('all', array('conditions'=>array('Scores.exam_user_id' => $user_id)));
        $exam_score = $exam_query->count();
        $this->set('exam_score', $exam_score);

        // トロフィー一覧を取得
        $trophies = $this->Trophies->find('all');
        $this->set('trophies',$trophies);

        // ここからミッションのフラグ確認追加です(ミッションの発行はMypageに集約)
        // 進行中ミッションを取得
        $running_mission = $this->UserMissionStatuses->find('all', array('conditions'=>array('UserMissionStatuses.user_id' => $user_id,'UserMissionStatuses.mission_completed' => 0)));
        // 進行中ミッションがなければ、新ミッション発行
        $running= $running_mission->count();
        if ($running === 0){
            // 成功件数に応じてミッションを追加
            $mission_query = $this->UserMissionStatuses->find('all', array('conditions'=>array('UserMissionStatuses.user_id' => $user_id,'UserMissionStatuses.mission_completed' => 1 )));
            $mission_count = $mission_query->count();
            // 成功件数+1のミッションを発行する
            $mission = $this->UserMissionStatuses->newEntity();
            $mission->user_id = $user_id;
            $mission->mission_id = $mission_count +1 ;
            $this->UserMissionStatuses->save($mission);
        }
        // 結合させたミッション進行度とミッションマスタを出してあげる
        $missions = $this->UserMissionStatuses->find('all', array('conditions'=>array('UserMissionStatuses.user_id' => $user_id,)))->contain(['MissionMasters']);
        $this->set('missions',$missions);
        // ここまで

    }

    // プロフィールの自己紹介欄を入力する画面
    public function edit()
    {
        // ログインチェック
        $user_id = $this->Auth->user('id');
        if ($user_id ==null)
        {
            return $this->redirect($this->Auth->redirectUrl('/users/login'));
        }

        // モデル取得
        $this->loadModel('UserProfiles');
        $this->loadModel('UserMissionStatuses');
        $post_profile = $this->UserProfiles->newEntity();
        $mission_statuses = $this->UserMissionStatuses->newEntity();
        // データ取得
        $user_profiles = $this->UserProfiles->find('all', array('conditions'=>array('UserProfiles.user_id' => $user_id)));
        $profile = $user_profiles->first();
        $mission_statuses = $this->UserMissionStatuses->find('all', array('conditions'=>array('UserMissionStatuses.user_id' => $user_id, 'UserMissionStatuses.mission_id' =>1)));
        $mission = $mission_statuses->first();

        // 投稿だったら受付、そうでなければ表示
        if ($this->request->is('post') && $profile != NULL) {
            // update
            // 明示的にプライマリキーを指定する事で更新扱いになる
            $post_profile = $this->UserProfiles->patchEntity($post_profile, $this->request->getData());
            $post_profile->id = $profile->id;
            $post_profile->user_id = $this->Auth->user('id');
            if ($this->UserProfiles->save($post_profile)) {
                $this->Flash->success(__('Your article has been saved.'));
                return $this->redirect(['action' => 'index']);
            }
        } else if ($this->request->is('post') && $profile == NULL) {
            $connection = ConnectionManager::get('default');
            $connection->begin();
            try{
                // insert
                // bodyは暗黙の取得、user_idは明示的に入力、2テーブル更新なので明示的にトランザクション宣言
                $post_profile = $this->UserProfiles->patchEntity($post_profile, $this->request->getData());
                $post_profile->user_id = $this->Auth->user('id');
                //　プロフィール新規登録
                if (!$this->UserProfiles->save($post_profile)) {
                    throw new Exception(Configure::read("M.ERROR.INVALID"));
                }
                // プロフィール新規登録なので、ミッション１は完了扱いになる

                $id = $mission->id;

                $user_mission_statuses_table = TableRegistry::get('UserMissionStatuses');
                $user_mission_statuses = $user_mission_statuses_table->get($id);
                $user_mission_statuses->id = $id;
                $user_mission_statuses->mission_completed = 1;
                $user_mission_statuses->mission_progress = 1;

                if (!$user_mission_statuses_table->save($user_mission_statuses)){
                    throw new Exception(Configure::read("M.ERROR.INVALID"));
                }
            } catch(Exception $e){
                $this->Flash->error($e);
                $connection->rollback(); //ロールバック
                return $this->redirect(['action' => 'index']);
            }
            $connection->commit();
            // 成功したなら成功表示して画面遷移
            $this->Flash->success(__('Your article has been saved.'));
            return $this->redirect(['action' => 'index']);
        // postでなければ表示を行う
        } else if ($profile != NULL){
            $this->set('body', $profile->body);
        } else {
            $this->set('body', NULL);
        }
    }

    public function view($id = null)
    {
        $this->loadModel('Articles');
        $article = $this->Articles->get($id);
        $this->set(compact('article'));
    }

    public function add()
    {
        $article = $this->Articles->newEntity();
        if ($this->request->is('post')) {
            $article = $this->Articles->patchEntity($article, $this->request->getData());
            // 投稿者IDを追記
            $article->user_id = $this->Auth->user('id');
            if ($this->Articles->save($article)) {
                $this->Flash->success(__('Your article has been saved.'));
                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('Unable to add your article.'));
        }
        $this->set('article', $article);
    }
}

src/Template/Mypages/edit.ctp
<meta charset="UTF-8"/>

<h1>Babylook Portal2 proto type system</h1>


<a href="./">戻る</a>
<table>

    <?= $this->Form->create() ?>
    <?= $this->Form->control('body', array('default' => $body, 'rows' => '5')) ?>
    <?= $this->Form->button(__('Submit')); ?>
    <?= $this->Form->end() ?>


</table>

src/Template/Mypages/index.ctp
<meta charset="UTF-8"/>

<h1>Babylook Portal2 proto type system</h1>

<table>
    <tr>
        <th><h5>あなたの名前：</h5></th><th><h5><?= $users->username ?></h5></th>
    </tr>
    <tr>
        <th><?= $this->Html->image('/img/default_icon.jpg'); ?></th>
    </tr>
    <tr>
        <th><h6><?= $this->Html->link('プロフィール更新', ['action' => 'edit']) ?></h6></th>
        <th><h6><?= $this->Html->link('画像を投稿', ['controller' =>'articles' ,'action' => 'add']) ?></h6></th>
        <th><h6><?= $this->Html->link('小説を投稿', ['controller' =>'novels' ,'action' => 'add']) ?></h6></th>

    </tr>

    <tr>
        <th>あなたがイイネされた回数は</th>
        <th><?=$my_score ?>回です</th>
    </tr>

    <tr>
        <th>あなたがイイネした回数は</th>
        <th><?=$exam_score ?>回です</th>
    </tr>


    <tr>
        <th>当サイトで用意された実績は</th>
    </tr>

    <?php foreach ($trophies as $trophie): ?>
    <tr>
        <td><?= $trophie->trophie_name ?></td>
    </tr>
    <?php endforeach; ?>

    <tr>
        <th><h5>プロフィール</h5></th>
        <th>
            <?php if($profile->body){
                echo nl2br(h($profile->body));
            } ?>

        </th>
    </tr>


    <tr>
        <th>クリアしたミッションは</th>
    </tr>

    <?php foreach ($missions as $mission): ?>
    <!-- todo:仮仕様として、ユーザーに発行されたミッションの全てを出し、Ｘ／Ｙで進捗率を出しています。％にする場合は応相談でお願いします 2017/06/14-->
            <td>ミッション番号<?= $mission->mission_master->id ?></td>
            <td>ミッション名<?= $mission->mission_master->mission_name  ?></td>
            <td>ミッション内容<?= $mission->mission_master->mission_description ?></td>
            <td>ミッション進捗率<?=$mission->mission_progress?> ／ <?= $mission->mission_master->mission_want_progres ?></td>
            <td>ミッション可否<?php if($mission->mission_completed==1){print "完了！";}else{print "実行中";} ?> </td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <th>Id</th>
        <th>作品Title</th>
        <th>サムネイル</th>
        <th>Created</th>
    </tr>

    <tr>
        <th>貴方が解除した実績は</th>

    </tr>

    <!--$my_scoreと$exam_score両方上回ったトロフィーのみ出すことにするロジック -->
    <?php foreach ($trophies as $trophie): ?>
        <tr>
            <td><?php if($exam_score >= $trophie->give_score && $my_score >= $trophie->take_score){
                    echo "ID:". $trophie->id;
                    echo $trophie->trophie_name;
                }
                ?>
            </td>
        </tr>
    <?php endforeach; ?>
    <!-- ここまで -->

    <!-- 自作投稿 -->
    <?php foreach ($articles as $article): ?>
        <tr>
            <td><?= $article->id ?></td>
            <td>
                <?= $this->Html->link($article->title, ['controller' =>'articles' ,'action' => 'view', $article->id]) ?>
            </td>

            <td>

                <?php $image_number = $article->image_number;   ?>

                <?php if ($image_number != null){
                    echo ($this->Html->image('/img/thumbnail/'.$image_number.".png"));
                }; ?>

            </th>

            <td>
                <?= $article->created->format(DATE_RFC850) ?>
            </td>
        </tr>
    <?php endforeach; ?>
    <!-- ここまで -->
</table>

src/Template/Mypages/view.ctp
<h1><?= h($article->title) ?></h1>
<p><?= h($article->body) ?></p>
<p><small>Created: <?= $article->created->format(DATE_RFC850) ?></small></p>